name: gendiff

on:
  push:
    branches:
      - main

jobs:
  gendiff-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Make commands
        run: make lint test
        id: test
          
         
